server:  
  port: ${PORT:8078}
spring:  
  application:
    name: zull
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
ribbon:
  eureka:
    enabled: true
